In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy as sp 
import seaborn as sns
import itertools
import scipy.stats as ssp
%matplotlib inline
import seaborn as sns


import math
import random
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
from scipy.stats import ttest_ind

In [2]:
# Z BAZY DANYCH ZOSTAŁ WYRZUCONY 1993 R.

In [2]:
df=pd.read_csv('globalterrorismdb_0718dist.csv',encoding='ISO-8859-1')

C:\Users\48500\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (4,6,31,33,61,62,63,76,79,90,92,94,96,114,115,121) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df2=df[['iyear','imonth','iday','country_txt','region_txt','city','attacktype1_txt','targtype1_txt','weaptype1_txt','nkill','natlty1_txt']]

In [4]:
df3 = df2.dropna()

In [5]:
df3

,iyear,imonth,iday,country_txt,region_txt,city,attacktype1_txt,targtype1_txt,weaptype1_txt,nkill,natlty1_txt
0,1970,7,2,Dominican Republic,Central America & Caribbean,Santo Domingo,Assassination,Private Citizens & Property,Unknown,1.0,Dominican Republic
1,1970,0,0,Mexico,North America,Mexico city,Hostage Taking (Kidnapping),Government (Diplomatic),Unknown,0.0,Belgium
2,1970,1,0,Philippines,Southeast Asia,Unknown,Assassination,Journalists & Media,Unknown,1.0,United States
5,1970,1,1,United States,North America,Cairo,Armed Assault,Police,Firearms,0.0,United States
6,1970,1,2,Uruguay,South America,Montevideo,Assassination,Police,Firearms,0.0,Uruguay
...,...,...,...,...,...,...,...,...,...,...,...
181686,2017,12,31,Somalia,Sub-Saharan Africa,Ceelka Geelow,Armed Assault,Military,Firearms,1.0,Somalia
181687,2017,12,31,Syria,Middle East & North Africa,Jableh,Bombing/Explosion,Military,Explosives,2.0,Russia
181688,2017,12,31,Philippines,Southeast Asia,Kubentog,Facility/Infrastructure Attack,Private Citizens & Property,Incendiary,0.0,Philippines
181689,2017,12,31,India,South Asia,Imphal,Bombing/Explosion,Government (General),Explosives,0.0,India
181690,2017,12,31,Philippines,Southeast Asia,Cotabato City,Bombing/Explosion,Unknown,Explosives,0.0,Philippines

In [6]:
# dodanie kolumny z indexem
df3['index'] = df3.index

C:\Users\48500\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:

# PRÓBA 1

# CZY W REGIONIE 'North America' JEST WIĘCEJ 'Bombing/Explosion' (wybuch bombowy) CZY Armed Assault (szturm zbrojony)??

In [27]:
mc = df3.where(df3.region_txt == 'North America').groupby(['nkill', 'attacktype1_txt']).count()['index'].reset_index()

     nkill                 attacktype1_txt  index
0      0.0                   Armed Assault    199
1      0.0                   Assassination     83
2      0.0               Bombing/Explosion   1422
3      0.0  Facility/Infrastructure Attack    883
4      0.0                       Hijacking     11
..     ...                             ...    ...
63   168.0               Bombing/Explosion      1
64   190.0                       Hijacking      1
65   329.0               Bombing/Explosion      1
66  1383.0                       Hijacking      1
67  1384.0                       Hijacking      1

[68 rows x 3 columns]

In [24]:
mc.groupby('attacktype1_txt').mean()

                                          nkill       index
attacktype1_txt
Armed Assault                         15.058824   26.000000
Assassination                          3.428571   36.285714
Bombing/Explosion                     49.727273  133.636364
Facility/Infrastructure Attack        11.000000  178.800000
Hijacking                            429.142857    2.571429
Hostage Taking (Barricade Incident)   10.571429    9.428571
Hostage Taking (Kidnapping)            5.000000   15.571429
Unarmed Assault                        2.750000   18.000000
Unknown                                1.000000    9.333333

In [28]:
mc.groupby('attacktype1_txt').describe()

                                    nkill                                     \
                                    count        mean         std  min   25%
attacktype1_txt
Armed Assault                        17.0   15.058824   19.077050  0.0  4.00
Assassination                         7.0    3.428571    2.992053  0.0  1.50
Bombing/Explosion                    11.0   49.727273  104.766494  0.0  2.50
Facility/Infrastructure Attack        5.0   11.000000   15.763883  0.0  1.00
Hijacking                             7.0  429.142857  655.367690  0.0  1.50
Hostage Taking (Barricade Incident)   7.0   10.571429   17.775049  0.0  1.50
Hostage Taking (Kidnapping)           7.0    5.000000    5.099020  0.0  1.50
Unarmed Assault                       4.0    2.750000    3.593976  0.0  0.75
Unknown                               3.0    1.000000    1.000000  0.0  0.50

                                                         index              \
                                      50%    75%     max count        mean
attacktype1_txt
Armed Assault                         8.0   13.0    59.0  17.0   26.000000
Assassination                         3.0    4.5     9.0   7.0   36.285714
Bombing/Explosion                     5.0   13.5   329.0  11.0  133.636364
Facility/Infrastructure Attack        2.0   15.0    37.0   5.0  178.800000
Hijacking                            44.0  786.5  1384.0   7.0    2.571429
Hostage Taking (Barricade Incident)   3.0    9.0    50.0   7.0    9.428571
Hostage Taking (Kidnapping)           4.0    6.5    15.0   7.0   15.571429
Unarmed Assault                       1.5    3.5     8.0   4.0   18.000000
Unknown                               1.0    1.5     2.0   3.0    9.333333


                                            std  min   25%  50%    75%     max
attacktype1_txt
Armed Assault                         53.116617  1.0  1.00  7.0  13.00   199.0
Assassination                         52.712156  1.0  3.50  6.0  52.00   136.0
Bombing/Explosion                    427.406896  1.0  1.00  1.0   3.50  1422.0
Facility/Infrastructure Attack       393.665086  1.0  1.00  3.0   6.00   883.0
Hijacking                              3.735289  1.0  1.00  1.0   1.50    11.0
Hostage Taking (Barricade Incident)   19.389492  1.0  1.00  1.0   4.50    53.0
Hostage Taking (Kidnapping)           29.494955  1.0  1.00  2.0  11.50    81.0
Unarmed Assault                       31.358146  1.0  1.75  3.0  19.25    65.0
Unknown                               10.115994  3.0  3.50  4.0  12.50    21.0

In [ ]:
# średnia liczba ofiar z podziałem na rodzaj ataku

In [19]:
a = 0.05
x = np.array(mc.loc[mc['attacktype1_txt'] == 'Bombing/Explosion' ]['index'])
y = np.array(mc.loc[mc['attacktype1_txt'] == 'Armed Assault']['index'])


print(ttest_ind(x,y))

Ttest_indResult(statistic=1.0366810629791907, pvalue=0.30943055121738644)

In [ ]:
# WNIOSKI no. 1
# P - value jest większe od poziomu istotności, więc hipotezę zerową można przyjąć za prawdziwą.

In [20]:
def test_bootstrap(x,y,n=1000,alpha=0.05):
    pvalues= []
    for i in range(n):                                        # losowanie ze zwracaniem ektora
        sample_x = np.random.choice(x,len(x),replace=True)
        sample_y = np.random.choice(y,len(y),replace=True)
        tst = ttest_ind(sample_x,sample_y)                    # test t-studenta
        p = (tst.pvalue < alpha)*1                            # istotnośc wyniku
        pvalues.append(p)
        
    print('Wynik testu istotny w {0} symulacji'.format(  "{:.1%}".format(np.mean(pvalues) )))

In [21]:
test_bootstrap(x,y)

Wynik testu istotny w 10.0% symulacji

In [ ]:
# WNIOSKI no. 2
# Wynikiem jest 10% przypadków, jest to niski wynik, więc nie można stwierdzić czy w tym regionie jest więcej
# wybuchów bombowych od szturmu zbrojonego

In [22]:
def test_symulacja(x,y,xm,y_m,xs,ys,n=1000,alpha=0.05):
    #xm,xs - średnia i odchylenie rozkałdu normalnego charakteryzująca różnicę ofiar dla wybuchów bombowych
    #ym,ys - to samo dla szturmu zbrojonego
    pvalues= []
    for i in range(n):
        #dodajemy wylosowane różnice
        sample_x = x + np.random.normal(xm,xs,len(x)).round()
        sample_y = y + np.random.normal(y_m,ys,len(y)).round()
        tst = ttest_ind(sample_x,sample_y)
        p = (tst.pvalue < alpha)*1
        pvalues.append(p)
    print('Wynik testu istotny w {0} symulacji'.format(  "{:.1%}".format(np.mean(pvalues) )))

In [ ]:
# dane z tabeli "mc.groupby('attacktype1_txt').describe()"

xm = 49.727273     # średnia 'Bombing/Explosion
xs = 104.766494    # odchylenie standardowe 'Bombing/Explosion
ym = 15.058824     # średnia Armed Assault
ys = 19.077050     # odchylenie standardowe Armed Assault

In [29]:

test_symulacja(x, y, 49.727273, 15.058824, 104.766494, 19.077050)

Wynik testu istotny w 1.7% symulacji

In [47]:
# metoda bootstrapu

def bootstrap_przedzial_roznicy(x,y,n=1000,alpha=0.05):
    diff = []
    for i in range(n):
        # losujemy e zwracaniem i liczymy różnicę
        sample_x = np.random.choice(x,len(x),replace=True)
        sample_y = np.random.choice(y,len(y),replace=True)
        diff.append(np.mean(sample_x)-np.mean(sample_y))
    #wyliczamy przedział ufności dla róznic
    orig_diff = np.mean(x) - np.mean(y)
    # przedział dolny 
    lcb =  orig_diff + np.percentile(diff,alpha/2)
    # przedział górny 
    ucb =  orig_diff + np.percentile(diff,1-alpha/2)
    include_zero = lcb < 0 and ucb >0 
    if include_zero:
        info = '0 zawiera się w przedziale ufności, więc nie mamy podstaw twierdzić że róznica jest istotna.'
    else:
        info = '0 nie zawiera się w przedziale ufności, więc przyjmujemy różnicę za istotną.'
    
    print('Przedział ufności różnic: ({0},{1})'.format(lcb.round(4),ucb.round(4)))
    print(info)

In [48]:
bootstrap_przedzial_roznicy(x,y,n=1000,alpha=0.05)

Przedział ufności różnic: (47.9102,61.1565)
0 nie zawiera się w przedziale ufności, więc przyjmujemy różnicę za istotną.

In [ ]:

# PRÓBA 2

# # CZY W REGIONIE 'Middle East & North Africa' JEST WIĘCEJ 'Hostage Taking (Kidnapping)' (branie zakładników - porwanie) 
# CZY 'Unarmed Assault' (atak uzbrojony)??

In [30]:
kc = mc = df3.where(df3.region_txt == 'Middle East & North Africa').groupby(['nkill', 'attacktype1_txt']).count()['index'].reset_index()

In [31]:
kc.groupby('attacktype1_txt').mean()

                                          nkill       index
attacktype1_txt
Armed Assault                         53.794521  123.315068
Assassination                         14.130435  181.173913
Bombing/Explosion                     69.162162  269.027027
Facility/Infrastructure Attack        32.000000   50.666667
Hijacking                             10.555556   13.888889
Hostage Taking (Barricade Incident)   35.280000    3.920000
Hostage Taking (Kidnapping)          118.436620   25.169014
Unarmed Assault                        6.500000   21.000000
Unknown                               32.456140   29.385965

In [32]:
kc.groupby('attacktype1_txt').describe()

                                     nkill                               \
                                     count        mean         std  min
attacktype1_txt
Armed Assault                         73.0   53.794521   85.208887  0.0
Assassination                         23.0   14.130435   11.951814  0.0
Bombing/Explosion                    111.0   69.162162   64.120560  0.0
Facility/Infrastructure Attack        21.0   32.000000   89.953877  0.0
Hijacking                              9.0   10.555556   19.609380  0.0
Hostage Taking (Barricade Incident)   25.0   35.280000   51.795688  0.0
Hostage Taking (Kidnapping)           71.0  118.436620  230.377996  0.0
Unarmed Assault                        8.0    6.500000    7.690439  0.0
Unknown                               57.0   32.456140   26.012408  0.0

                                                                  index  \
                                       25%   50%     75%     max  count
attacktype1_txt
Armed Assault                        18.00  37.0   57.00   670.0   73.0
Assassination                         5.50  11.0   21.50    47.0   23.0
Bombing/Explosion                    27.50  55.0   87.00   383.0  111.0
Facility/Infrastructure Attack        5.00  10.0   20.00   422.0   21.0
Hijacking                             2.00   4.0    6.00    62.0    9.0
Hostage Taking (Barricade Incident)   6.00  15.0   46.00   230.0   25.0
Hostage Taking (Kidnapping)          17.50  40.0  112.50  1570.0   71.0
Unarmed Assault                       1.75   3.5    7.75    21.0    8.0
Unknown                              14.00  28.0   44.00   151.0   57.0

                                                                             \
                                           mean          std  min  25%  50%
attacktype1_txt
Armed Assault                        123.315068   473.083088  1.0  1.0  3.0
Assassination                        181.173913   513.412970  1.0  1.0  5.0
Bombing/Explosion                    269.027027  1457.500934  1.0  1.5  5.0
Facility/Infrastructure Attack        50.666667   215.552623  1.0  1.0  1.0
Hijacking                             13.888889    33.164154  1.0  1.0  3.0
Hostage Taking (Barricade Incident)    3.920000     7.745536  1.0  1.0  2.0
Hostage Taking (Kidnapping)           25.169014   117.471454  1.0  1.0  2.0
Unarmed Assault                       21.000000    36.897542  1.0  2.0  2.0
Unknown                               29.385965    70.432276  1.0  1.0  6.0


                                       75%      max
attacktype1_txt
Armed Assault                        20.00   2947.0
Assassination                        37.00   2199.0
Bombing/Explosion                    22.50  13806.0
Facility/Infrastructure Attack        3.00    991.0
Hijacking                             3.00    102.0
Hostage Taking (Barricade Incident)   3.00     40.0
Hostage Taking (Kidnapping)           5.50    920.0
Unarmed Assault                      17.25    102.0
Unknown                              22.00    428.0

In [ ]:
# czy średnia liczba ofiar z podziałem na rodzaj ataku

In [39]:
a = 0.05
c = np.array(mc.loc[mc['attacktype1_txt'] == 'Hostage Taking (Kidnapping)' ]['index'])
d = np.array(mc.loc[mc['attacktype1_txt'] == 'Unarmed Assault']['index'])

print(ttest_ind(c, d))

Ttest_indResult(statistic=0.09931758751777887, pvalue=0.9211442305422184)

In [ ]:
# WNIOSKI no. 1
# P - value jest (bliskie 1.0) zdecydowanie większe od poziomu istotności, więc hipotezę zerową można przyjąć za prawdziwą.

In [40]:
def test_bootstrap(c, d, n=1000,alpha=0.05):
    pvalues= []
    for i in range(n):                                        # losowanie ze zwracaniem ektora
        sample_x = np.random.choice(x,len(x),replace=True)
        sample_y = np.random.choice(y,len(y),replace=True)
        tst = ttest_ind(sample_x,sample_y)                    # test t-studenta
        p = (tst.pvalue < alpha)*1                            # istotnośc wyniku
        pvalues.append(p)
        
    print('Wynik testu istotny w {0} symulacji'.format(  "{:.1%}".format(np.mean(pvalues) )))

In [41]:
test_bootstrap(x,y)

Wynik testu istotny w 10.4% symulacji

In [ ]:
# WNIOSKI no. 2
# Wynikiem jest 10% przypadków, jest to niski wynik, więc nie można stwierdzić czy w tym regionie jest więcej
# atatków terrorystycznych typu 'branie zakładników - porwanie' czy atak uzbrojony

In [43]:
def test_symulacja(c,d,xm,y_m,xs,ys,n=1000,alpha=0.05):
    #cm,cs - średnia i odchylenie rozkałdu normalnego charakteryzująca różnicę ofiar dla wybuchów bombowych
    #dm,ds - to samo dla szturmu zbrojonego
    pvalues= []
    for i in range(n):
        #dodajemy wylosowane różnice
        sample_x = x + np.random.normal(xm,xs,len(x)).round()
        sample_y = y + np.random.normal(y_m,ys,len(y)).round()
        tst = ttest_ind(sample_x,sample_y)
        p = (tst.pvalue < alpha)*1
        pvalues.append(p)
    print('Wynik testu istotny w {0} symulacji'.format(  "{:.1%}".format(np.mean(pvalues) )))

In [42]:
# dane z tabeli "kc.groupby('attacktype1_txt').describe()"

cm = 118.436620         # średnia 'Hostage Taking (Kidnapping)'
cs = 230.377996         # odchylenie standardowe 'Hostage Taking (Kidnapping)'
dm = 6.5                # średnia 'Unarmed Assault'
ds = 7.690439           # odchylenie standardowe 'Unarmed Assault'

In [44]:
test_symulacja(c, d, 118.436620, 6.5, 230.377996, 7.690439 )

Wynik testu istotny w 38.4% symulacji

In [45]:
# Metoda bootstrap

def bootstrap_przedzial_roznicy(c,d,n=1000,alpha=0.05):
    diff = []
    for i in range(n):
        # losujemy e zwracaniem i liczymy różnicę
        sample_c = np.random.choice(c,len(c),replace=True)
        sample_d = np.random.choice(d,len(d),replace=True)
        diff.append(np.mean(sample_c)-np.mean(sample_d))
    #wyliczamy przedział ufności dla róznic
    orig_diff = np.mean(c) - np.mean(d)
    # przedział dolny 
    lcb =  orig_diff + np.percentile(diff,alpha/2)
    # przedział górny 
    ucb =  orig_diff + np.percentile(diff,1-alpha/2)
    include_zero = lcb < 0 and ucb >0 
    if include_zero:
        info = '0 zawiera się w przedziale ufności, więc nie mamy podstaw twierdzić że róznica jest istotna.'
    else:
        info = '0 nie zawiera się w przedziale ufności, więc przyjmujemy różnicę za istotną.'
    
    print('Przedział ufności różnic: ({0},{1})'.format(lcb.round(4),ucb.round(4)))
    print(info)

In [46]:
bootstrap_przedzial_roznicy(c,d,n=1000,alpha=0.05)

Przedział ufności różnic: (-47.673,-33.0453)
0 nie zawiera się w przedziale ufności, więc przyjmujemy różnicę za istotną.